title: Yaxin's Homepage
logo: /assets/img/yaxin_disney.jpg
description: Hey! It’s great that you come across here.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: /README.md
  another_url: another value
